[package]
name = "json2env"
version = "0.1.0"
edition = "2021"
authors = ["Marcello Lamonaca <marcello@lamonaca.eu>"]
description = "JSON to Env Var converter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.3", features = ["derive", "color"] }
serde_json = "1.0.96"
